name: NestJS Backend CI/CD DEPLOYMENT

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i -g yarn
      - run: yarn
      - run: echo "${{ secrets.PROD_ENV }}" | base64 -d > .env
      - run: yarn build
      - run: |
          if npx pm2 list | grep -q 'my-app'; then
            npx pm2 stop my-app
          else
            echo "Process my-app not found, skipping stop."
          fi
      - run: npx pm2 start dist/main.js --name my-app
